<?php
// $Id$

/**
 * @file
 * A module integrating DEA Master Calendar with Drupal.
 *
 * This module provides a block with an events stream and a page that displays the same events in a calendar format. 
 * 
 */
 
/**
 * Implements hook_help().
 */
function mastercal_help($path, $arg) {
  if ($path == 'admin/help#mastercal') {
    return t('A module to display Calendar data from Master Calendar.');
  }
}

/**
 * Implements hook_permission().
 * - The option to give this permission will show up under Mastercal in the permissions page.
 */
function mastercal_permission() {
  return array(
    'administer mastercal' => array(
      'title' => t('Administer mastercal'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mastercal_menu() {
  $items = array();

  //path to config
  $items['admin/config/user-interface/mastercal'] = array(
    'title' => 'Master Calendar',
    'description' => 'Add, remove and configure calendars.',
    'page callback' => 'mastercal_set_admin',
    'access arguments' => array('administer mastercal'),
    'file' => 'mastercal.admin.inc',
  );
    
  //callback url for adding a new calendar
  //the function mastercal_set_add_form() in the admin.inc file provides the form
  $items['admin/config/user-interface/mastercal/add-set'] = array(
    'title' => 'Add a calendar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mastercal_set_add_form'),
    'access arguments' => array('administer mastercal'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'mastercal.admin.inc',
  );
  
  //passes the calendar id of the item you are trying to remove
  //the access callback should be changed to be more restrictive
  $items['admin/config/user-interface/mastercal/%/delete'] = array(
    'title' => 'Delete a calendar.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mastercal_set_delete_form', 4),
    'access callback' => True,
    'access arguments' => array('administer mastercal'),
    'file' => 'mastercal.admin.inc',
  );
  
  
  $items['org/testcal'] = array(
    'title' => 'Tests',
    'page callback' => 'mastercal_testview',
    'access callback' => TRUE,
  );
  
  return $items;
}

function mastercal_cron() {
  if (variable_get('MASTERCAL_AUTH')) {
  //initialize an instance of the mastercalSOAP class then call the GetEvents() method
  //the calendars being queried for the events list are loaded from the database
    $events = client()->GetEvents();
    //dprint_r($events);
    //initialize the JSON string so I can append to it later
    //there may be a better way to create this JSON
    $nodes = array(
      'saved' => 0,
      'passed' => 0
    );
    $widgetData  = '';
    
    foreach ($events as $id => $event) {
      $cid = $id;
      $did = $event['EventDetailID'];
      $contact_name = $event['ContactName'];
      $contact_email = $event['ContactEmail'];
      
      $event_loc = (!empty($event['Location'])) ? $event['Location'] : NULL;
      $event_loc_url = (!empty($event['LocationURL'])) ? $event['LocationURL'] : NULL;
      
      $node = new stdClass();
      $node->type = 'node_event';
      $node->language = LANGUAGE_NONE;
      node_object_prepare($node);
      $node->title = $event['Title'];
      $node->body['und'][0]['value'] = $event['Description'];
      $node->body['und'][0]['format'] = 'filtered_html';
      $node->field_event_cid['und'][0]['value'] = $cid;
      $node->field_event_did['und'][0]['value'] = $did;
      
      $event_data = client()->GetEvent($did);
        if (isset($event_data[0]['Image'])) {
          $image = base64_decode($event_data[0]['Image']);
          $file = file_save_data($image, 'public://' . $event_data[0]['ImageName'], FILE_EXISTS_REPLACE);
          $node->field_event_image['und']['0']['fid'] = $file->fid;
          //node_save($node);
        }
      
      $node->field_event_contact['und'][0]['value'] = $contact_name;
      $n_dates = count($event['EventDate']);
      if ($n_dates > 1) {
        //dprint_r('more');
        $count = 0;
        foreach ($event['EventDate'] as $day) {
          //dprint_r($day);
          $date = explode('T', $day['Start']);
          $time = explode('-', $date[1]);
          $datetime = $date[0] . ' ' . $time[0];
          $the_date = gmdate('Y-m-d H:i:s', strtotime($datetime));
          //date_default_timezone_set("UTC");
          //$UTCdate = (string) date("Y-d-m G:i:00", $the_date);
          $node->field_event_date['und'][$count]['value'] = $the_date;
          $node->field_event_date['und'][$count]['value2'] = $the_date;
          //dprint_r($count);
          $count += 1;
        }
      } 
      else {
        //dprint_r($event['EventDate']);
        $date = explode('T', $event['EventDate'][0]['Start']);
        $time = explode('-', $date[1]);
        $datetime = $date[0] . ' ' . $time[0];
        $the_date = gmdate('Y-m-d H:i:s', strtotime($datetime));

        //date_default_timezone_set("UTC");
        //$UTCdate = (string) date("Y-d-m G:i:00", $the_date);
        $node->field_event_date['und'][0]['value'] = $the_date;
        $node->field_event_date['und'][0]['value2'] = $the_date;
        $node->field_event_date['und'][0]['date_type'] = 'datetime';

      }
      #dprint_r($datetime);
      
      $node->field_event_location['und'][0]['value'] = $event_loc;
      if (!empty($event_loc_url)) {
        $node->field_event_url['und'][0]['value'] = $event_loc_url;
      }
      if (!empty($event['EventTypeName'])) {
        $type_name = $event['EventTypeName'];    
        mastercal_create_terms(array($type_name));
        $tid = db_query_range('SELECT tid FROM {taxonomy_term_data} WHERE name = :name ORDER BY tid DESC', 0, 
          1, array(':name' => $type_name))->fetchField();
          
        if (!empty($tid)) {
          $node->field_event_type['und'][0]['tid'] = $tid;
        }
      }
      $query = new EntityFieldQuery;
      $result = $query
        ->entityCondition('entity_type', 'node')
        ->propertyCondition('type', 'node_event')
        ->fieldCondition('field_event_cid', 'value', $cid, '=')
        ->execute();
        
      //dprint_r($result);
      if (empty($result)) {
        node_submit($node);
        node_save($node);
        $nodes['saved'] += 1;
        $node_re = node_load($node->nid);
        node_save($node_re);
      }
      else {
        $nodes['passed'] += 1;
      }
    }

    drupal_set_message(t("@saved nodes created, @pass events skipped.", array(
      '@saved' => $nodes['saved'], 
      '@pass' => $nodes['passed'])
      ) 
    );
  }
}

/**
 * Create taxonomy lists.
 */
function mastercal_create_terms($list) {
$jobs = array();
  //grabs the list of vocabularies  
  $vocabularies = taxonomy_get_vocabularies();
  foreach ($vocabularies as $voc) {
    if ($voc->machine_name == 'event_types') {
      $vid = $voc->vid;
    }
  }
  //grabs the terms from the chosen vocabulary
  $existing = taxonomy_get_tree($vid);
  
  $loaded_terms = array();
  foreach ($existing as $job_rank) {           
    $loaded_terms[] = $job_rank->name;     
  }
  foreach ($list as $entry) {
    if (is_array($entry)) {
      if (!isset($jobs[$entry['title']])) {
        $jobs[$entry['title']] = False;
      }
    }
    else {
      if (!isset($jobs[$entry])) {
        $jobs[$entry] = False;
      }
    }
  }
  
  if (!empty($loaded_terms)) {
    foreach ($jobs as $new_term => $val) {

      if (!in_array($new_term, $loaded_terms)) {
        taxonomy_term_save((object) array(
          'name' => t($new_term),
          'vid' => $vid,
        )); 
      }
    }
  }
  else { 
    foreach ($jobs as $new_term => $val) {
      //print_r($new_term);
      taxonomy_term_save((object) array(
        'name' => t($new_term),
        'vid' => $vid,
      )); 
    }
  }
}

/**
 * Test view function.
 */
function mastercal_testview() {
  if (variable_get('MASTERCAL_AUTH')) {
  //initialize an instance of the mastercalSOAP class then call the GetEvents() method
  //the calendars being queried for the events list are loaded from the database
    $events = client()->GetEvents();
    //dprint_r($events);
    //initialize the JSON string so I can append to it later
    //there may be a better way to create this JSON


    
    foreach ($events as $id => $event) {
      $cid = $id;
      $did = $event['EventDetailID'];
    //print_r($event);

      $n_dates = count($event['EventDate']);
      if ($n_dates > 1) {
        //dprint_r('more');
        $count = 0;
        foreach ($event['EventDate'] as $day) {
          //dprint_r($day);
          $date = explode('T', $day['Start']);
         
          $time = explode('-', $date[1]);
          $datetime = $date[0] . ' ' . $time[0];

          $the_date = strtotime($datetime);
          //echo(date_default_timezone_get() . "<br />");
          //echo(date("Y-d-mTG:i:sz",$the_date) . "<br />");
          //echo("\n");
          //echo($datetime);
          
          echo(gmdate('Y-m-d H:i:s', $the_date));
          //dprint_r($count);
          $count += 1;
        }
      } 
      else {
        //dprint_r($event['EventDate']);
        $date = explode('T', $event['EventDate'][0]['Start']);
        $time = explode('-', $date[1]);
        $datetime = $date[0] . ' ' . $time[0];
        $the_date = strtotime($datetime);
        echo("\n");
          echo(gmdate('Y-m-d H:i:s', $the_date));
          
          //echo(date_default_timezone_get() . "<br />");
          //echo(date("Y-d-mTG:i:sz",$the_date) . "<br />");
          

      }
     

    }


  }
  
  
  
  $return = array(
    'calendar' => array(
      '#markup' => 'Tes',
      '#prefix' => '<div id="mastercal_page">',
      '#suffix' => '</div>',
    ),
  );
  
  return $return;
}



/**
 * 
 * Instantiate mastercalSOAP client.
 * @return mastercalSOAP
 */
function client() {
  require_once('mastercal_class.inc');
  $client = new mastercalSOAP();
    
  return $client;
}

/**
 * Helper function to check if a calendar already exists in {mastercal_source}.
 *   
 * @return boolean
 *   TRUE if calendar exists.
 *   FALSE if calendar does not exist.
 */
function cal_exists($cid) {
  return (bool) db_query_range('SELECT 1 FROM {mastercal_source} WHERE cid = :cid', 0, 1, array(':cid' => $cid))->fetchField();
}

/**
 * Helper function to check if {mastercal_source} is empty.
 *   
 * @return boolean
 *   TRUE if any records exist.
 *   FALSE if table is empty.
 */ 
function records_exist() {
  return (bool) db_query_range('SELECT 1 FROM {mastercal_source}', 0, 1)->fetchField();
}

function mastercal_save(&$cal) {
  // Save the calendar ID and its name to teh database
 $return = db_insert('mastercal_source')
            ->fields(array(
                'title' => $cal['Name'],
                'cid' => (int)$cal['CalendarID'],
              )
            )
            ->execute();
  return $return;
}

function mastercal_load() {
//for simple queries it is more economical to use db_query and SQL than to use the new Drupal 7 methods
  $result = db_query("SELECT title, cid FROM {mastercal_source}");
  return $result;
}
function mastercal_delete($cid) {
  $deleted = db_delete('mastercal_source')
  ->condition('cid', $cid)
  ->execute();
  return $deleted;
}
